FROM node:18-bullseye-slim

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends libssl1.1 ca-certificates \
  && rm -rf /var/lib/apt/lists/*
COPY package.json package-lock.json ./
RUN npm ci

COPY . .
ENV NODE_ENV=production
RUN npx prisma generate

EXPOSE 4000 4001
CMD ["node", "server/index.js"]
